Symbol *check_add(Symbol*, Symbol*);
Symbol *check_substr(Symbol*, Symbol*);
Symbol *check_uminus(Symbol*);
Symbol *check_division(Symbol*, Symbol*);
Symbol *check_mult(Symbol*, Symbol*);
Symbol *check_eq(Symbol*, Symbol*);
Symbol *check_lt(Symbol*, Symbol*);
Symbol *check_gt(Symbol*, Symbol*);
Symbol *check_le(Symbol*, Symbol*);
Symbol *check_ge(Symbol*, Symbol*);
Symbol *check_ne(Symbol*, Symbol*);